[package]
name = "umc_xmly"
version = "0.1.12"
edition = "2021"

[dependencies]
aes = "0.8.4"
byteorder = "1.5.0"
cbc = "0.1.2"
cipher = "0.4.4"
hex = "0.4.3"
lazy_static = "1.5.0"
thiserror = "2.0.7"
umc_utils = { path = "../utils" }
