[package]
name = "umc_ncm"
version = "0.1.9"
edition = "2021"

[dependencies]
aes = "0.8.4"
byteorder = "1.5.0"
cipher = { version = "0.4.4", features = ["block-padding"] }
crc = "3.2.1"
itertools = "0.13.0"
thiserror = "2.0.7"
umc_utils = { path = "../utils" }
