[package]
name = "umc_qrc"
version = "0.1.9"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
itertools = "0.13.0"
miniz_oxide = "0.8.0"
thiserror = "2.0.7"
umc_qmc = { path = "../qmc" }
hex = "0.4.3"
